// GENERATED by scripts/build-episodes.mjs. Do not edit.
const VERSION = 'mm-679b8a1160';
const PRECACHE = [
  "/",
  "/tools.html",
  "/offline.html",
  "/manifest.webmanifest",
  "/episodes/episode.css",
  "/episodes/episode.js",
  "/signup.js",
  "/feedback.js",
  "/player.js",
  "/discover.js",
  "/site.js",
  "/favicon.svg",
  "/icon-192.png",
  "/icon-512.png",
  "/channel-poster.webp",
  "/host-leo.jpg",
  "/host-dan.jpg"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  // Audio streams (Range requests) always go to the network.
  if (req.headers.has('range') || /\.(mp3|m4a)$/i.test(url.pathname)) return;

  if (req.mode === 'navigate') {
    // Pages: network first so new episodes appear, cache as the offline fallback.
    const key = new Request(url.origin + url.pathname);
    e.respondWith(
      fetch(req)
        .then((res) => {
          if (res.ok) { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(key, copy)); }
          return res;
        })
        .catch(() => caches.match(key).then((hit) => hit || caches.match('/offline.html')))
    );
    return;
  }

  // Static assets: cache first, refreshed in the background.
  e.respondWith(
    caches.match(req).then((hit) => {
      const net = fetch(req)
        .then((res) => {
          if (res.ok) { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(req, copy)); }
          return res;
        })
        .catch(() => hit);
      return hit || net;
    })
  );
});
